// ------------------------------------------------------------------------------
//  <autogenerated>
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTitle("Castle.MonoRail for .NETFramework v4.0")]
[assembly: System.Reflection.AssemblyProduct("Castle.MonoRail")]
[assembly: System.Reflection.AssemblyVersion("3.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.0.0.0")]
